In [1]:
from keras.constraints import *

Using TensorFlow backend.


In [2]:
curv = CurvatureConstraint(m=20.0)

In [3]:
import numpy as np
from keras import backend as K

In [4]:
x = np.array([4, 1, 0, 1, 4])

In [5]:
y = np.array([x, -x, 2*x, 2*x, -x, x])
y

array([[ 4,  1,  0,  1,  4],
       [-4, -1,  0, -1, -4],
       [ 8,  2,  0,  2,  8],
       [ 8,  2,  0,  2,  8],
       [-4, -1,  0, -1, -4],
       [ 4,  1,  0,  1,  4]])

In [6]:
W = K.variable(value=y)
W

In [7]:
ret = curv.__call__(W)

In [8]:
K.eval(ret)

array([[ 4.,  1.,  0.,  1.,  4.],
       [-4., -1.,  0., -1., -4.],
       [ 8.,  2.,  0.,  2.,  8.],
       [ 8.,  2.,  0.,  2.,  8.],
       [-4., -1.,  0., -1., -4.],
       [ 4.,  1.,  0.,  1.,  4.]], dtype=float32)

In [9]:
curv2 = CurvatureConstraint(m=1.0)
W2 = K.variable(value=y)
ret2 = curv2.__call__(W2)
K.eval(ret2)

array([[ 3. ,  1.5,  1. ,  1.5,  3. ],
       [-3. , -1.5, -1. , -1.5, -3. ],
       [ 5. ,  3.5,  3. ,  3.5,  5. ],
       [ 5. ,  3.5,  3. ,  3.5,  5. ],
       [-3. , -1.5, -1. , -1.5, -3. ],
       [ 3. ,  1.5,  1. ,  1.5,  3. ]], dtype=float32)